# Generated by Django 5.2.12 on 2026-09-04 16:23

import apps.accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_two_factor_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='api_token',
            field=models.CharField(default=apps.accounts.models.generate_api_token_id, max_length=128, unique=True),
        ),
    ]
