ITEMS = [
    (1, "gosta_de_balancar"),
    (2, "interesse_outras_criancas"),
    (3, "gosta_de_subir"),
    (4, "brinca_esconder_mostrar"),
    (5, "brinca_faz_de_conta"),
    (6, "aponta_para_pedir"),
    (7, "aponta_para_mostrar_interesse"),
    (8, "brinca_corretamente_com_objetos"),
    (9, "traz_objetos_para_mostrar"),
    (10, "contato_visual"),
    (11, "hipersensibilidade_a_ruido"),
    (12, "sorri_em_resposta"),
    (13, "imita_o_adulto"),
    (14, "responde_ao_nome"),
    (15, "segue_apontar"),
    (16, "ja_sabe_andar"),
    (17, "olha_para_o_que_o_adulto_olha"),
    (18, "movimentos_estranhos_dedos_rosto"),
    (19, "busca_atencao_para_atividade"),
    (20, "suspeita_de_surdez"),
    (21, "entende_o_que_dizem"),
    (22, "fica_aereo_ou_deambula"),
    (23, "checa_reacao_facial"),
]

VALID_RESPONSES = ["1", "0"]

CRITICAL_ITEMS = {2, 7, 9, 13, 14, 15}

FAILURE_RULES = {
    1: "Não",
    2: "Não",
    3: "Não",
    4: "Não",
    5: "Não",
    6: "Não",
    7: "Não",
    8: "Não",
    9: "Não",
    10: "Não",
    11: "Sim",
    12: "Não",
    13: "Não",
    14: "Não",
    15: "Não",
    16: "Não",
    17: "Não",
    18: "Sim",
    19: "Não",
    20: "Sim",
    21: "Não",
    22: "Sim",
    23: "Não",
}
