from __future__ import annotations

from docx.shared import Cm, Inches


TABLE_LAYOUT_SPECS = {
    "wisc": {
        "style": None,
        "alignment": "left",
        "shading_profile": "wisc",
        "paragraph_profile": "wisc",
        "header_no_wrap_rows": (0,),
        "border_profile": "subtle_grid",
        "vertical_align_center": True,
        "widths": [
            Inches(2028 / 1440),
            Inches(1525 / 1440),
            Inches(1366 / 1440),
            Inches(1492 / 1440),
            Inches(1400 / 1440),
            Inches(1523 / 1440),
        ],
    },
    "wisc_linguagem": {
        "style": None,
        "alignment": "left",
        "shading_profile": "wisc",
        "paragraph_profile": "wisc",
        "header_no_wrap_rows": (0,),
        "border_profile": "subtle_grid",
        "vertical_align_center": True,
        "widths": [
            Inches(1736 / 1440),
            Inches(1632 / 1440),
            Inches(1464 / 1440),
            Inches(1594 / 1440),
            Inches(1499 / 1440),
            Inches(1409 / 1440),
        ],
    },
    "wisc_gnosias": {
        "style": None,
        "alignment": "left",
        "shading_profile": "wisc",
        "paragraph_profile": "wisc",
        "header_no_wrap_rows": (0,),
        "border_profile": "subtle_grid",
        "vertical_align_center": True,
        "widths": [
            Inches(1980 / 1440),
            Inches(1579 / 1440),
            Inches(1415 / 1440),
            Inches(1546 / 1440),
            Inches(1451 / 1440),
            Inches(1363 / 1440),
        ],
    },
    "etdah_pais": {
        "style": None,
        "alignment": "center",
        "shading_profile": "banded_fdt",
        "paragraph_profile": "banded_first_left",
        "header_no_wrap_rows": (0,),
        "header_no_wrap_rows_with_title": (0, 1),
        "first_col_no_wrap": True,
        "border_profile": "subtle_grid",
        "vertical_align_center": True,
        "widths": [
            Inches(7.16 / 2.54),
            Inches(2.8 / 2.54),
            Inches(1.51 / 2.54),
            Inches(1.92 / 2.54),
            Inches(3.1 / 2.54),
        ],
    },
    "wais_linguagem": {
        "style": None,
        "alignment": "left",
        "shading_profile": "wisc",
        "paragraph_profile": "wisc",
        "header_no_wrap_rows": (0,),
        "border_profile": "subtle_grid",
        "vertical_align_center": True,
        "widths": [
            Cm(3.07),
            Cm(2.72),
            Cm(2.39),
            Cm(2.66),
            Cm(2.67),
            Cm(2.96),
        ],
    },
    "wais_gnosias": {
        "style": None,
        "alignment": "left",
        "shading_profile": "wisc",
        "paragraph_profile": "wisc",
        "header_no_wrap_rows": (0,),
        "border_profile": "subtle_grid",
        "vertical_align_center": True,
        "widths": [
            Cm(3.07),
            Cm(2.72),
            Cm(2.39),
            Cm(2.66),
            Cm(2.67),
            Cm(2.96),
        ],
    },
    "wais_funcoes_executivas": {
        "style": None,
        "alignment": "left",
        "shading_profile": "wisc",
        "paragraph_profile": "wisc",
        "header_no_wrap_rows": (0,),
        "border_profile": "subtle_grid",
        "vertical_align_center": True,
        "widths": [
            Cm(3.43),
            Cm(2.65),
            Cm(2.33),
            Cm(2.58),
            Cm(2.59),
            Cm(2.88),
        ],
    },
    "wais_memoria": {
        "style": None,
        "alignment": "left",
        "shading_profile": "wisc",
        "paragraph_profile": "wisc",
        "header_no_wrap_rows": (0,),
        "border_profile": "subtle_grid",
        "vertical_align_center": True,
        "widths": [
            Cm(3.50),
            Cm(2.51),
            Cm(2.21),
            Cm(2.45),
            Cm(2.46),
            Cm(3.34),
        ],
    },
    "wais_etdah_ad": {
        "style": None,
        "alignment": "center",
        "shading_profile": "title_header_plain_body",
        "paragraph_profile": "banded_first_left",
        "header_no_wrap_rows": (0,),
        "header_no_wrap_rows_with_title": (0, 1),
        "first_col_no_wrap": True,
        "border_profile": "subtle_grid",
        "vertical_align_center": True,
        "title_font_color": "FFFFFF",
        "widths": [
            Cm(8.47),
            Cm(2.43),
            Cm(1.31),
            Cm(1.67),
            Cm(2.60),
        ],
    },
    "wasi_verbal": {
        "style": None,
        "alignment": "left",
        "shading_profile": "header_light_body",
        "paragraph_profile": "wisc",
        "header_no_wrap_rows": (0,),
        "border_profile": "subtle_grid",
        "vertical_align_center": True,
        "widths": [
            Inches(4.45 / 2.54),
            Inches(2.41 / 2.54),
            Inches(2.41 / 2.54),
            Inches(2.41 / 2.54),
            Inches(2.29 / 2.54),
            Inches(2.92 / 2.54),
        ],
    },
    "wasi_execucao": {
        "style": None,
        "alignment": "left",
        "shading_profile": "header_light_body",
        "paragraph_profile": "wisc",
        "header_no_wrap_rows": (0,),
        "border_profile": "subtle_grid",
        "vertical_align_center": True,
        "widths": [
            Inches(4.45 / 2.54),
            Inches(2.41 / 2.54),
            Inches(2.41 / 2.54),
            Inches(2.41 / 2.54),
            Inches(2.29 / 2.54),
            Inches(2.92 / 2.54),
        ],
    },
    "wasi_etdah_ad": {
        "style": None,
        "alignment": "center",
        "shading_profile": "title_header_light_body",
        "paragraph_profile": "banded_first_left",
        "header_no_wrap_rows": (0,),
        "header_no_wrap_rows_with_title": (0, 1),
        "first_col_no_wrap": True,
        "border_profile": "subtle_grid",
        "vertical_align_center": True,
        "title_font_color": "FFFFFF",
        "widths": [
            Inches(9.02 / 2.54),
            Inches(2.24 / 2.54),
            Inches(1.23 / 2.54),
            Inches(1.56 / 2.54),
            Inches(2.44 / 2.54),
        ],
    },
    "wais_bpa": {
        "style": None,
        "alignment": "left",
        "shading_profile": "header_light_body",
        "paragraph_profile": "banded_first_left",
        "header_no_wrap_rows": (0,),
        "border_profile": "subtle_grid",
        "vertical_align_center": True,
        "widths": [Cm(7.20), Cm(2.30), Cm(2.80), Cm(4.18)],
    },
    "wisc_bpa": {
        "style": None,
        "alignment": "left",
        "shading_profile": "header_light_body",
        "paragraph_profile": "banded_first_left",
        "header_no_wrap_rows": (0,),
        "border_profile": "subtle_grid",
        "vertical_align_center": True,
        "widths": [Cm(5.81), Cm(2.76), Cm(2.41), Cm(5.50)],
    },
    "wasi_bpa": {
        "style": None,
        "alignment": "left",
        "shading_profile": "title_header_light_body",
        "paragraph_profile": "banded_first_left",
        "header_no_wrap_rows": (0,),
        "header_no_wrap_rows_with_title": (0, 1),
        "border_profile": "subtle_grid",
        "vertical_align_center": True,
        "title_font_color": "FFFFFF",
        "widths": [Cm(5.97), Cm(2.92), Cm(2.54), Cm(5.08)],
    },
    "bpa": {
        "style": None,
        "alignment": "left",
        "shading_profile": "bpa",
        "paragraph_profile": "banded_first_left",
        "header_no_wrap_rows": (0,),
        "header_no_wrap_rows_with_title": (0, 1),
        "border_profile": "subtle_grid",
        "vertical_align_center": True,
        "widths": [Inches(2.35), Inches(1.15), Inches(1.00), Inches(2.00)],
    },
    "ravlt": {
        "style": None,
        "alignment": "center",
        "vertical_align_center": True,
        "widths": [
            Inches(3.11 / 2.54),
            Inches(0.93 / 2.54), Inches(0.93 / 2.54), Inches(0.93 / 2.54), Inches(0.93 / 2.54),
            Inches(0.93 / 2.54),
            Inches(0.93 / 2.54),
            Inches(0.93 / 2.54),
            Inches(0.93 / 2.54),
            Inches(0.82 / 2.54),
            Inches(1.36 / 2.54),
            Inches(1.36 / 2.54),
            Inches(1.2 / 2.54),
            Inches(1.2 / 2.54),
        ],
    },
    "wais_ravlt": {
        "style": None,
        "alignment": "center",
        "vertical_align_center": True,
        "widths": [
            Cm(3.11),
            Cm(0.93), Cm(0.93), Cm(0.93), Cm(0.93),
            Cm(0.93),
            Cm(0.90),
            Cm(0.93),
            Cm(0.93),
            Cm(0.82),
            Cm(1.36),
            Cm(1.36),
            Cm(1.20),
            Cm(1.20),
        ],
    },
    "wisc_ravlt": {
        "style": None,
        "alignment": "center",
        "vertical_align_center": True,
        "widths": [
            Cm(3.02),
            Cm(0.95), Cm(0.95), Cm(0.95), Cm(0.95),
            Cm(0.95),
            Cm(0.92),
            Cm(0.95),
            Cm(0.95),
            Cm(0.84),
            Cm(1.36),
            Cm(1.36),
            Cm(1.20),
            Cm(1.13),
        ],
    },
    "wasi_ravlt": {
        "style": None,
        "alignment": "center",
        "vertical_align_center": True,
        "widths": [
            Cm(3.10),
            Cm(0.93), Cm(0.93), Cm(0.93), Cm(0.93),
            Cm(0.93),
            Cm(0.93),
            Cm(0.93),
            Cm(0.93),
            Cm(0.82),
            Cm(1.36),
            Cm(1.36),
            Cm(1.20),
            Cm(1.20),
        ],
    },
    "fdt": {
        "style": None,
        "alignment": "center",
        "shading_profile": "fdt",
        "paragraph_profile": "banded_first_left",
        "header_no_wrap_rows": (0, 1),
        "border_profile": "subtle_grid",
        "vertical_align_center": True,
        "widths": [
            Inches(1295 / 1440),
            Inches(1377 / 1440),
            Inches(1411 / 1440),
            Inches(673 / 1440),
            Inches(1284 / 1440),
            Inches(3304 / 1440),
        ],
    },
    "wais_fdt": {
        "style": None,
        "alignment": "center",
        "shading_profile": "title_header_firstcol_light",
        "paragraph_profile": "banded_first_left",
        "header_no_wrap_rows": (0, 1),
        "border_profile": "subtle_grid",
        "vertical_align_center": True,
        "widths": [Cm(2.30), Cm(2.52), Cm(2.62), Cm(1.27), Cm(2.36), Cm(5.40)],
    },
    "wisc_fdt": {
        "style": None,
        "alignment": "center",
        "shading_profile": "titlegreen_header_firstcol_light",
        "paragraph_profile": "banded_first_left",
        "header_no_wrap_rows": (0, 1),
        "border_profile": "subtle_grid",
        "vertical_align_center": True,
        "widths": [Cm(2.28), Cm(2.43), Cm(2.49), Cm(1.19), Cm(2.26), Cm(5.83)],
    },
    "wasi_fdt": {
        "style": None,
        "alignment": "center",
        "shading_profile": "title_header_firstcol_light",
        "paragraph_profile": "banded_first_left",
        "header_no_wrap_rows": (0, 1),
        "border_profile": "subtle_grid",
        "vertical_align_center": True,
        "title_font_color": "FFFFFF",
        "widths": [Cm(2.28), Cm(2.43), Cm(2.49), Cm(1.19), Cm(2.26), Cm(5.83)],
    },
    "etdah": {
        "style": None,
        "alignment": "center",
        "shading_profile": "banded_fdt",
        "paragraph_profile": "banded_first_left",
        "header_no_wrap_rows": (0,),
        "header_no_wrap_rows_with_title": (0, 1),
        "first_col_no_wrap": True,
        "border_profile": "subtle_grid",
        "vertical_align_center": True,
        "widths": [Inches(3.3), Inches(1.15), Inches(0.65), Inches(0.8), Inches(1.25)],
    },
    "scared": {
        "style": None,
        "alignment": "center",
        "shading_profile": "banded_fdt",
        "paragraph_profile": "banded_first_left",
        "header_no_wrap_rows": (0,),
        "header_no_wrap_rows_with_title": (0, 1),
        "border_profile": "subtle_grid",
        "vertical_align_center": True,
        "widths": [Inches(2.3), Inches(0.9), Inches(0.9), Inches(1.1), Inches(1.1)],
    },
    "wisc_scared_parent": {
        "style": None,
        "alignment": "center",
        "shading_profile": "title_header_plain_body",
        "paragraph_profile": "banded_first_left",
        "header_no_wrap_rows": (0,),
        "header_no_wrap_rows_with_title": (0, 1),
        "border_profile": "subtle_grid",
        "vertical_align_center": True,
        "widths": [Cm(5.30), Cm(2.91), Cm(2.90), Cm(2.01), Cm(3.36)],
    },
    "wisc_scared_self": {
        "style": None,
        "alignment": "center",
        "shading_profile": "title_header_plain_body",
        "paragraph_profile": "banded_first_left",
        "header_no_wrap_rows": (0,),
        "header_no_wrap_rows_with_title": (0, 1),
        "border_profile": "subtle_grid",
        "vertical_align_center": True,
        "widths": [Cm(5.30), Cm(2.91), Cm(2.90), Cm(2.01), Cm(3.36)],
    },
    "scared_parent": {
        "style": None,
        "alignment": "center",
        "shading_profile": "banded_fdt",
        "paragraph_profile": "banded_first_left",
        "header_no_wrap_rows": (0,),
        "header_no_wrap_rows_with_title": (0, 1),
        "border_profile": "subtle_grid",
        "vertical_align_center": True,
        "widths": [Inches(2.3), Inches(0.9), Inches(0.9), Inches(1.1), Inches(1.1)],
    },
    "wasi_scared_parent": {
        "style": None,
        "alignment": "center",
        "shading_profile": "title_header_light_body",
        "paragraph_profile": "banded_first_left",
        "header_no_wrap_rows": (0,),
        "header_no_wrap_rows_with_title": (0, 1),
        "border_profile": "subtle_grid",
        "vertical_align_center": True,
        "title_font_color": "FFFFFF",
        "widths": [Cm(5.51), Cm(2.89), Cm(3.05), Cm(2.13), Cm(2.92)],
    },
    "scared_self": {
        "style": None,
        "alignment": "center",
        "shading_profile": "banded_fdt",
        "paragraph_profile": "banded_first_left",
        "header_no_wrap_rows": (0,),
        "header_no_wrap_rows_with_title": (0, 1),
        "border_profile": "subtle_grid",
        "vertical_align_center": True,
        "widths": [Inches(2.0), Inches(1.15), Inches(0.8), Inches(0.9), Inches(1.35)],
    },
    "wasi_scared_self": {
        "style": None,
        "alignment": "center",
        "shading_profile": "title_header_light_body",
        "paragraph_profile": "banded_first_left",
        "header_no_wrap_rows": (0,),
        "header_no_wrap_rows_with_title": (0, 1),
        "border_profile": "subtle_grid",
        "vertical_align_center": True,
        "title_font_color": "FFFFFF",
        "widths": [Cm(5.32), Cm(3.06), Cm(2.13), Cm(2.39), Cm(3.59)],
    },
    "epq": {
        "style": None,
        "alignment": "center",
        "shading_profile": "epq",
        "paragraph_profile": "center_all",
        "border_profile": "subtle_grid",
        "widths": [Inches(2.0), Inches(0.8), Inches(0.8), Inches(0.8), Inches(1.2)],
    },
    "wisc_epq": {
        "style": None,
        "alignment": "center",
        "shading_profile": "epq_model",
        "paragraph_profile": "center_all",
        "header_no_wrap_rows": (0, 1),
        "border_profile": "subtle_grid",
        "vertical_align_center": True,
        "widths": [Cm(6.55), Cm(2.28), Cm(2.66), Cm(2.27), Cm(2.73)],
    },
    "wasi_epq": {
        "style": None,
        "alignment": "center",
        "shading_profile": "epq_model",
        "paragraph_profile": "center_all",
        "header_no_wrap_rows": (0, 1),
        "border_profile": "subtle_grid",
        "vertical_align_center": True,
        "title_font_color": "FFFFFF",
        "widths": [Cm(5.64), Cm(2.35), Cm(1.96), Cm(4.18), Cm(2.35)],
    },
    "srs2": {
        "style": None,
        "alignment": "center",
        "shading_profile": "banded_fdt",
        "paragraph_profile": "banded_first_left",
        "header_no_wrap_rows": (0,),
        "header_no_wrap_rows_with_title": (0, 1),
        "last_col_no_wrap": True,
        "border_profile": "subtle_grid",
        "vertical_align_center": True,
        "widths": [Inches(2.2), Inches(1.05), Inches(0.7), Inches(0.75), Inches(1.95)],
    },
    "wais_srs2": {
        "style": None,
        "alignment": "center",
        "shading_profile": "title_header_plain_body",
        "paragraph_profile": "banded_first_left",
        "header_no_wrap_rows": (0,),
        "header_no_wrap_rows_with_title": (0, 1),
        "last_col_no_wrap": True,
        "border_profile": "subtle_grid",
        "vertical_align_center": True,
        "title_font_color": "FFFFFF",
        "widths": [Cm(5.61), Cm(2.67), Cm(1.66), Cm(1.83), Cm(4.70)],
    },
    "wisc_srs2": {
        "style": None,
        "alignment": "center",
        "shading_profile": "title_header_plain_body",
        "paragraph_profile": "banded_first_left",
        "header_no_wrap_rows": (0,),
        "header_no_wrap_rows_with_title": (0, 1),
        "last_col_no_wrap": True,
        "border_profile": "subtle_grid",
        "vertical_align_center": True,
        "widths": [Cm(5.46), Cm(2.61), Cm(1.64), Cm(1.80), Cm(4.97)],
    },
    "wasi_srs2": {
        "style": None,
        "alignment": "center",
        "shading_profile": "title_header_light_body",
        "paragraph_profile": "banded_first_left",
        "header_no_wrap_rows": (0,),
        "header_no_wrap_rows_with_title": (0, 1),
        "last_col_no_wrap": True,
        "border_profile": "subtle_grid",
        "vertical_align_center": True,
        "title_font_color": "FFFFFF",
        "widths": [Cm(5.59), Cm(2.67), Cm(1.78), Cm(1.91), Cm(4.95)],
    },
    "scale_summary": {
        "style": None,
        "alignment": "center",
        "border_profile": "subtle_grid",
        "widths": [Inches(2.2), Inches(3.0)],
    },
    "wais_ebadep": {
        "style": None,
        "alignment": "center",
        "shading_profile": "wais_ebadep",
        "paragraph_profile": "default",
        "header_rows_with_title": (),
        "border_profile": "subtle_grid",
        "vertical_align_center": True,
        "title_font_color": "FFFFFF",
        "widths": [Cm(4.71), Cm(11.77)],
    },
    "wasi_ebadep": {
        "style": None,
        "alignment": "center",
        "shading_profile": "wasi_ebadep",
        "paragraph_profile": "default",
        "header_no_wrap_rows_with_title": (0, 1),
        "border_profile": "subtle_grid",
        "vertical_align_center": True,
        "title_font_color": "FFFFFF",
        "widths": [Cm(6.13), Cm(10.35)],
    },
    "bai_scores": {
        "style": None,
        "alignment": "center",
        "shading_profile": "bai_scores",
        "paragraph_profile": "bai_scores",
        "border_profile": "subtle_grid",
        "vertical_align_center": True,
        "widths": [Inches(3.8), Inches(1.55), Inches(1.55)],
    },
    "bfp": {
        "style": None,
        "alignment": "center",
        "shading_profile": "none",
        "paragraph_profile": "center_all",
        "border_profile": "bottom_only",
    },
    "wasi_bfp": {
        "style": None,
        "alignment": "center",
        "shading_profile": "none",
        "paragraph_profile": "center_all",
        "border_profile": "bottom_only",
        "vertical_align_center": True,
        "widths": [Cm(6.10), Cm(3.59), Cm(2.65), Cm(4.15)],
    },
    "wisc_etdah_pais": {
        "style": None,
        "alignment": "center",
        "shading_profile": "title_header_plain_body",
        "paragraph_profile": "banded_first_left",
        "header_no_wrap_rows": (0,),
        "header_no_wrap_rows_with_title": (0, 1),
        "first_col_no_wrap": True,
        "border_profile": "subtle_grid",
        "vertical_align_center": True,
        "title_font_color": "FFFFFF",
        "widths": [Cm(7.16), Cm(2.80), Cm(1.51), Cm(1.92), Cm(3.10)],
    },
    "wisc_etdah_ad": {
        "style": None,
        "alignment": "center",
        "shading_profile": "title_header_plain_body",
        "paragraph_profile": "banded_first_left",
        "header_no_wrap_rows": (0,),
        "header_no_wrap_rows_with_title": (0, 1),
        "first_col_no_wrap": True,
        "border_profile": "subtle_grid",
        "vertical_align_center": True,
        "title_font_color": "FFFFFF",
        "widths": [Cm(8.48), Cm(2.43), Cm(1.31), Cm(1.67), Cm(2.59)],
    },
    "default": {
        "style": None,
        "alignment": "center",
        "shading_profile": "default",
        "paragraph_profile": "default",
        "border_profile": "subtle_grid",
    },
}
